version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10.0
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
 
      - run: npm helloo.js
      - run: node myfirst.js
